# Generated by Django 4.2.3 on 2023-07-16 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('startupapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainer_name', models.CharField(max_length=50)),
                ('trainer_designation', models.CharField(max_length=100)),
                ('trainer_experience', models.DecimalField(decimal_places=2, max_digits=5)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='startupapp.courses')),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('candidateId', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('fatherName', models.CharField(max_length=50)),
                ('phoneNumber', models.CharField(max_length=15)),
                ('alternateNumber', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('collageName', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=150)),
                ('landmark', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=15)),
                ('pincode', models.IntegerField()),
                ('companyName', models.CharField(blank=True, max_length=150, null=True)),
                ('designation', models.CharField(max_length=150)),
                ('qualification', models.CharField(max_length=50)),
                ('computerKnowledge', models.CharField(max_length=50)),
                ('Courses', models.CharField(max_length=50)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('trainer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='startupapp.trainer')),
            ],
        ),
    ]
