# Generated by Django 4.2.3 on 2023-07-19 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startupapp', '0003_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='street',
            field=models.CharField(max_length=200),
        ),
    ]
